const Task=require('../models/Task');const Project=require('../models/Project');const User=require('../models/User');
async function refs(body){if(body.project&&!await Project.exists({_id:body.project}))return 'Project not found';if(body.assignee&&!await User.exists({_id:body.assignee}))return 'Assignee not found';}
const populated=q=>q.populate([{path:'project',select:'name status'},{path:'assignee',select:'name email role'}]);
exports.create=async(req,res,next)=>{try{const message=await refs(req.body);if(message)return res.status(404).json({success:false,message});const t=await Task.create(req.body);res.status(201).json({success:true,data:await populated(t)});}catch(e){next(e)}};
exports.list=async(req,res,next)=>{try{res.json({success:true,data:await populated(Task.find().sort('-createdAt'))});}catch(e){next(e)}};
exports.get=async(req,res,next)=>{try{const t=await populated(Task.findById(req.params.id));if(!t)return res.status(404).json({success:false,message:'Task not found'});res.json({success:true,data:t});}catch(e){next(e)}};
exports.update=async(req,res,next)=>{try{const message=await refs(req.body);if(message)return res.status(404).json({success:false,message});const t=await Task.findById(req.params.id);if(!t)return res.status(404).json({success:false,message:'Task not found'});const project=await Project.findById(t.project);const userId=req.user._id.toString();const isAssignee=t.assignee&&t.assignee.toString()===userId;const isProjectOwner=project&&project.owner.toString()===userId;if(!isAssignee&&!isProjectOwner)return res.status(403).json({success:false,message:'Only the task assignee or project owner can update this task.'});Object.assign(t,req.body);await t.save({validateModifiedOnly:true});await t.populate([{path:'project',select:'name status'},{path:'assignee',select:'name email role'}]);res.json({success:true,data:t});}catch(e){next(e)}};
exports.status=async(req,res,next)=>{try{const t=await populated(Task.findByIdAndUpdate(req.params.id,{status:req.body.status},{new:true,runValidators:true}));if(!t)return res.status(404).json({success:false,message:'Task not found'});res.json({success:true,data:t});}catch(e){next(e)}};
exports.remove=async(req,res,next)=>{try{const t=await Task.findById(req.params.id);if(!t)return res.status(404).json({success:false,message:'Task not found'});const project=await Project.findById(t.project);const userId=req.user._id.toString();const isAssignee=t.assignee&&t.assignee.toString()===userId;const isProjectOwner=project&&project.owner.toString()===userId;if(!isAssignee&&!isProjectOwner)return res.status(403).json({success:false,message:'Only the task assignee or project owner can delete this task.'});await t.deleteOne();res.json({success:true,data:t});}catch(e){next(e)}};
