const router = require('express').Router();
const { body } = require('express-validator');
const controller = require('../controllers/authController');
const validate = require('../middleware/validate');
const auth = require('../middleware/auth');
const authLimiter = require('../middleware/rateLimiter');
const { PASSWORD_RULE, PASSWORD_MESSAGE } = require('../validators/passwordPolicy');
router.post('/register', authLimiter, [body('name').trim().notEmpty().withMessage('Name is required'), body('email').isEmail().withMessage('A valid email is required').normalizeEmail(), body('password').matches(PASSWORD_RULE).withMessage(PASSWORD_MESSAGE)], validate, controller.register);
router.post('/login', authLimiter, [body('email').isEmail().withMessage('A valid email is required').normalizeEmail(), body('password').notEmpty().withMessage('Password is required')], validate, controller.login);
router.get('/me', auth, controller.me);
module.exports = router;
