import { useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import ConnectedApp from './AppConnected';
import { AuthProvider, useAuth } from './hooks/useAuth.jsx';

const passwordPattern = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9]).{8,15}$/;
function AuthShell({ children, title, subtitle }) { return <main className="grid min-h-screen place-items-center bg-[#f6f7fb] p-4"><section className="card w-full max-w-md p-7 sm:p-9"><div className="mb-7 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-600 font-bold text-white">P</span><div><b className="block text-lg">Paceflow</b><span className="text-xs text-slate-500">Developer productivity</span></div></div><h1 className="text-2xl font-bold">{title}</h1><p className="mt-2 text-sm text-slate-500">{subtitle}</p>{children}</section></main>; }
function Login({ showRegister }) { const { login } = useAuth(); const [form, setForm] = useState({ email: '', password: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { await login(form); } catch (reason) { setError(reason.message || 'Invalid email or password.'); } finally { setBusy(false); } }; return <AuthShell title="Welcome back" subtitle="Log in to continue to your workspace."><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-medium">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="focus mt-1 w-full rounded-lg border border-slate-200 p-2.5" autoComplete="email" /></label><label className="block text-sm font-medium">Password<input required type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="focus mt-1 w-full rounded-lg border border-slate-200 p-2.5" autoComplete="current-password" /></label>{error && <p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={busy} className="focus w-full rounded-lg bg-blue-600 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{busy ? 'Logging in…' : 'Login'}</button></form><p className="mt-5 text-center text-sm text-slate-500">Don't have an account? <button onClick={showRegister} className="font-semibold text-blue-600">Create one</button></p></AuthShell>; }
function Register({ showLogin }) { const { register } = useAuth(); const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event) => { event.preventDefault(); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); if (!passwordPattern.test(form.password)) return setError('Password does not meet the requirements.'); setBusy(true); setError(''); try { await register({ name: form.name, email: form.email, password: form.password }); } catch (reason) { setError(reason.message || 'Unable to create account.'); } finally { setBusy(false); } }; return <AuthShell title="Create your account" subtitle="Start organizing your developer workflow."><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-medium">Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="focus mt-1 w-full rounded-lg border border-slate-200 p-2.5" autoComplete="name" /></label><label className="block text-sm font-medium">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="focus mt-1 w-full rounded-lg border border-slate-200 p-2.5" autoComplete="email" /></label><label className="block text-sm font-medium">Password<input required type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="focus mt-1 w-full rounded-lg border border-slate-200 p-2.5" autoComplete="new-password" /></label><label className="block text-sm font-medium">Confirm password<input required type="password" value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} className="focus mt-1 w-full rounded-lg border border-slate-200 p-2.5" autoComplete="new-password" /></label><p className="rounded-lg bg-slate-50 p-3 text-xs leading-5 text-slate-600">Use 8–15 characters with uppercase, lowercase, a number, and a special character. Example: <b>Purvika@123</b></p>{error && <p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<button disabled={busy} className="focus w-full rounded-lg bg-blue-600 py-2.5 text-sm font-semibold text-white disabled:opacity-60">{busy ? 'Creating account…' : 'Create account'}</button></form><p className="mt-5 text-center text-sm text-slate-500">Already have an account? <button onClick={showLogin} className="font-semibold text-blue-600">Login</button></p></AuthShell>; }
function AuthGate() { const { loading, user } = useAuth(); const [registering, setRegistering] = useState(false); if (loading) return <main className="grid min-h-screen place-items-center bg-[#f6f7fb]"><ShieldCheck className="animate-pulse text-blue-600" size={34} /></main>; if (!user) return registering ? <Register showLogin={() => setRegistering(false)} /> : <Login showRegister={() => setRegistering(true)} />; return <ConnectedApp />; }
export default function AppAuthenticated() { return <AuthProvider><AuthGate /></AuthProvider>; }
